### ISSUE TITLE
In Lab 8 (Lift and Shift) lack of restoreDBCS invoked in pom.xml file

### ISSUE THREAD

**Issue by MaciejGruszka** [oracle-weblogic/weblogic-innovation-seminars#3]
I think there is an issue - you created a script restoreDBCS.sh - but that script is not invoked AFAICS

**Comment by nagypeter** [comment]
Correct. Ankit created, but never used and tested. My approach is always
when you create/prepare database the script first remove/clean the user and
it's objects.
